# Generated by Django 3.2.4 on 2021-06-15 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_chart_chart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='chart',
            field=models.ImageField(upload_to='charts/%Y'),
        ),
    ]
