# Generated by Django 3.2.4 on 2021-06-20 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_chart_chart'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='error',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
